### ISSUE TITLE
Exposed OpenWeatherMap API Key ! 

### ISSUE THREAD

**Issue by itskdhere** [sanajitjana/Weather-App#1]
Your OpenWeatherMap API Key is exposed in the code.

Your key is:
 ```bash
6768b2e5b4a36c16f6a94477cd18cbc9
```

**Comment by behind24proxies** [comment]
thanks for the free api key

**Comment by itskdhere** [comment]
> thanks for the free api key
> 

Lol 😂
But don't abuse that key..😆

**Comment by sanajitjana** [comment]
@itskdhere 
@behind24proxies 

No problem guys, you can use it
It's free for everyone
